version: '3.7'

services:
  mysql:
    container_name: ecommerce-database
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
