version: '3.7'

services:
  db1:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce-auth
  db2:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce-product
  db3:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce-cart

networks:
  ecommerce-network:
    driver: bridge
